[package]
name = "ryzen_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
libryzenadj = { git = "https://gitlab.com/chironjit/libryzenadj-rs.git" }